import type {
  Annotation,
  CallSite,
  ComplexityResult,
  DependencyEdge,
  DiagnosticItem,
  EnclosingClass,
  ExportedSymbol,
  FileNode,
  FileSummary,
  HoverInfo,
  ParameterInfo,
  ProjectInfo,
  RhizomeAnalytics,
  RhizomeCopyMoveRequest,
  RhizomeCopyMoveResult,
  RhizomeRenameRequest,
  RhizomeRenameResult,
  RhizomeStatus,
  RhizomeSymbol,
  ScopeVariable,
  SearchResult,
  SymbolBody,
  SymbolDefinition,
  SymbolLocation,
  TestFunction,
} from '../types'
import { get, post } from './http'

export const rhizomeApi = {
  analytics: () => get<RhizomeAnalytics>('/rhizome/analytics'),
  annotations: (file: string) => get<Annotation[]>('/rhizome/annotations', { file }),
  callSites: (file: string, fn?: string) => get<CallSite[]>('/rhizome/call-sites', { file, function: fn ?? '' }),
  complexity: (file: string) => get<ComplexityResult[]>('/rhizome/complexity', { file }),
  copySymbol: (body: RhizomeCopyMoveRequest) => post<RhizomeCopyMoveResult>('/rhizome/copy-symbol', body),
  definition: (file: string, symbol: string) => get<SymbolDefinition>('/rhizome/definition', { file, symbol }),
  dependencies: (file: string) => get<DependencyEdge[]>('/rhizome/dependencies', { file }),
  diagnostics: (file?: string) => get<DiagnosticItem[]>('/rhizome/diagnostics', { file: file ?? '' }),
  enclosingClass: (file: string, line: number) => get<EnclosingClass>('/rhizome/enclosing-class', { file, line: String(line) }),
  exports: (file: string) => get<ExportedSymbol[]>('/rhizome/exports', { file }),
  files: (path?: string, depth?: number) => get<FileNode[]>('/rhizome/files', { depth: depth ? String(depth) : '', path: path ?? '' }),
  hover: (file: string, line: number, column: number) =>
    get<HoverInfo>('/rhizome/hover', { column: String(column), file, line: String(line) }),
  moveSymbol: (body: RhizomeCopyMoveRequest) => post<RhizomeCopyMoveResult>('/rhizome/move-symbol', body),
  parameters: (file: string, symbol: string) => get<ParameterInfo[]>('/rhizome/parameters', { file, symbol }),
  project: () => get<ProjectInfo>('/rhizome/project'),
  references: (file: string, line: number, column: number) =>
    get<SymbolLocation[]>('/rhizome/references', { column: String(column), file, line: String(line) }),
  renameSymbol: (body: RhizomeRenameRequest) => post<RhizomeRenameResult>('/rhizome/rename', body),
  scope: (file: string, line: number) => get<ScopeVariable[]>('/rhizome/scope', { file, line: String(line) }),
  search: (pattern: string, path?: string) => get<SearchResult[]>('/rhizome/search', { path: path ?? '', pattern }),
  status: () => get<RhizomeStatus>('/rhizome/status'),
  structure: (file: string, depth?: number) => get<RhizomeSymbol[]>('/rhizome/structure', { depth: depth ? String(depth) : '', file }),
  summary: (file: string) => get<FileSummary>('/rhizome/summary', { file }),
  switchProject: (path: string) => post<ProjectInfo>('/rhizome/project', { path }),
  symbolBody: (file: string, symbol: string, line?: number) =>
    get<SymbolBody>('/rhizome/symbol-body', { file, line: line ? String(line) : '', symbol }),
  symbols: (file: string) => get<RhizomeSymbol[]>('/rhizome/symbols', { file }),
  tests: (file: string) => get<TestFunction[]>('/rhizome/tests', { file }),
  typeDefinitions: (file: string) => get<RhizomeSymbol[]>('/rhizome/type-definitions', { file }),
}
