import {
  ActionIcon,
  Badge,
  Box,
  Button,
  Card,
  Checkbox,
  Collapse,
  Divider,
  Group,
  Paper,
  Select,
  Stack,
  Text,
  TextInput,
  Title,
  Tooltip,
} from '@mantine/core'
import { notifications } from '@mantine/notifications'
import { IconChevronDown, IconChevronUp, IconCopy, IconGripVertical, IconPlus, IconRefresh } from '@tabler/icons-react'
import { useCallback, useEffect, useRef, useState } from 'react'

import type { StatuslineSegment } from '../../lib/api/statusline'
import { useSaveStatuslineConfig, useStatuslineConfig } from '../../lib/queries/statusline'

// ─────────────────────────────────────────────────────────────────────────────
// Types & constants
// ─────────────────────────────────────────────────────────────────────────────

const ALL_SEGMENT_NAMES = [
  'context',
  'usage',
  'cost',
  'model',
  'savings',
  'degradation',
  'branch',
  'workspace',
  'context-bar',
  'context-metrics',
  'hyphae',
  'heartbeat',
  'bridge',
  'canopy-adoption',
  'canopy-notifications',
  'cortina',
] as const

type SegmentName = (typeof ALL_SEGMENT_NAMES)[number]

// Mock values used in the preview panel (no live annulus process required)
const SEGMENT_MOCK: Record<SegmentName, string | null> = {
  branch: 'git: main',
  bridge: null,
  'canopy-adoption': null,
  'canopy-notifications': '2 new',
  context: 'ctx: ▲ 45%',
  'context-bar': '[ctx ████░░░░░░ 45%]',
  'context-metrics': 'ctx 45%',
  cortina: 'cortina: 3 hooks',
  cost: '$0.08',
  degradation: null,
  heartbeat: 'agent: idle',
  hyphae: 'hy: active',
  model: 'claude-opus-4-7',
  savings: 'mycelium: 17%',
  usage: '90.0k/200k',
  workspace: 'ws: basidiocarp',
}

// ─────────────────────────────────────────────────────────────────────────────
// ANSI color map
// ─────────────────────────────────────────────────────────────────────────────

const ANSI_COLOR_MAP: Record<string, string> = {
  '2': '#888888',
  '30': '#000000',
  '31': '#c0392b',
  '32': '#27ae60',
  '33': '#f39c12',
  '34': '#2980b9',
  '35': '#8e44ad',
  '36': '#16a085',
  '37': '#bdc3c7',
  '90': '#555555',
  '91': '#e74c3c',
  '92': '#2ecc71',
  '93': '#f1c40f',
  '94': '#3498db',
  '95': '#9b59b6',
  '96': '#1abc9c',
  '97': '#ecf0f1',
}

function ansiToCSS(code: string | null): string | undefined {
  if (!code) return undefined
  // Support compound codes like "1;32" — use the last color code found
  const parts = code.split(';')
  for (let i = parts.length - 1; i >= 0; i--) {
    const color = ANSI_COLOR_MAP[parts[i]]
    if (color) return color
  }
  return undefined
}

// ─────────────────────────────────────────────────────────────────────────────
// TOML serializer (for clipboard copy)
// ─────────────────────────────────────────────────────────────────────────────

function configToToml(segments: StatuslineSegment[], separator: string): string {
  const lines: string[] = ['# Generated by cap statusline editor', '', '[general]', `separator = "${separator}"`, '']
  for (const seg of segments) {
    lines.push('[[segments]]')
    lines.push(`name = "${seg.name}"`)
    lines.push(`enabled = ${seg.enabled}`)
    if (seg.color) lines.push(`color = "${seg.color}"`)
    if (seg.separator) lines.push(`separator = "${seg.separator}"`)
    if (seg.line === 2) lines.push(`line = ${seg.line}`)
    lines.push('')
  }
  return lines.join('\n')
}

// ─────────────────────────────────────────────────────────────────────────────
// Drag-to-reorder (no external library — pointer events)
// ─────────────────────────────────────────────────────────────────────────────

interface DragState {
  dragIndex: number
  overIndex: number
}

function useDragReorder(items: StatuslineSegment[], onReorder: (next: StatuslineSegment[]) => void) {
  const dragRef = useRef<DragState | null>(null)

  function handleDragStart(index: number) {
    dragRef.current = { dragIndex: index, overIndex: index }
  }

  function handleDragOver(index: number) {
    if (!dragRef.current || dragRef.current.overIndex === index) return
    dragRef.current.overIndex = index
  }

  function handleDrop() {
    const state = dragRef.current
    if (!state) return
    dragRef.current = null

    const { dragIndex, overIndex } = state
    if (dragIndex === overIndex) return

    const next = [...items]
    const [moved] = next.splice(dragIndex, 1)
    next.splice(overIndex, 0, moved)
    onReorder(next)
  }

  return { handleDragOver, handleDragStart, handleDrop }
}

// ─────────────────────────────────────────────────────────────────────────────
// SegmentRow component
// ─────────────────────────────────────────────────────────────────────────────

interface SegmentRowProps {
  segment: StatuslineSegment
  index: number
  onChange: (index: number, updates: Partial<StatuslineSegment>) => void
  onRemove: (index: number) => void
  onDragStart: (index: number) => void
  onDragOver: (index: number) => void
  onDrop: () => void
}

function SegmentRow({ index, onChange, onDragOver, onDragStart, onDrop, onRemove, segment }: SegmentRowProps) {
  const [expanded, setExpanded] = useState(false)

  return (
    <Paper
      draggable
      onDragOver={(e) => {
        e.preventDefault()
        onDragOver(index)
      }}
      onDragStart={() => onDragStart(index)}
      onDrop={onDrop}
      p='xs'
      style={{ cursor: 'default' }}
      withBorder
    >
      <Group
        gap='xs'
        wrap='nowrap'
      >
        <ActionIcon
          color='gray'
          size='sm'
          style={{ cursor: 'grab' }}
          variant='subtle'
        >
          <IconGripVertical size={14} />
        </ActionIcon>

        <Checkbox
          checked={segment.enabled}
          onChange={(e) => onChange(index, { enabled: e.currentTarget.checked })}
          size='sm'
        />

        <Text
          fw={500}
          size='sm'
          style={{ flex: 1 }}
        >
          {segment.name}
        </Text>

        {segment.line === 2 && (
          <Badge
            color='blue'
            size='xs'
            variant='light'
          >
            line 2
          </Badge>
        )}

        <Tooltip label='Remove segment'>
          <ActionIcon
            color='red'
            onClick={() => onRemove(index)}
            size='sm'
            variant='subtle'
          >
            &times;
          </ActionIcon>
        </Tooltip>

        <ActionIcon
          onClick={() => setExpanded((v) => !v)}
          size='sm'
          variant='subtle'
        >
          {expanded ? <IconChevronUp size={14} /> : <IconChevronDown size={14} />}
        </ActionIcon>
      </Group>

      <Collapse in={expanded}>
        <Stack
          gap='xs'
          mt='xs'
          pl={32}
        >
          <TextInput
            description='ANSI color code, e.g. 32 for green, 1;33 for bold yellow. Leave blank for default.'
            label='Color'
            onChange={(e) => {
              const val = e.currentTarget.value.trim()
              onChange(index, { color: val.length > 0 ? val : null })
            }}
            placeholder='e.g. 32'
            size='xs'
            value={segment.color ?? ''}
          />
          <TextInput
            description='Override the global separator after this segment. Leave blank to use the global separator.'
            label='Per-segment separator'
            onChange={(e) => {
              const val = e.currentTarget.value
              onChange(index, { separator: val.length > 0 ? val : null })
            }}
            placeholder='e.g.  |  or leave blank'
            size='xs'
            value={segment.separator ?? ''}
          />
          <Select
            data={[
              { label: 'Line 1', value: '1' },
              { label: 'Line 2', value: '2' },
            ]}
            label='Line'
            onChange={(v) => onChange(index, { line: v === '2' ? 2 : 1 })}
            size='xs'
            value={String(segment.line)}
          />
        </Stack>
      </Collapse>
    </Paper>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Preview panel
// ─────────────────────────────────────────────────────────────────────────────

interface PreviewPanelProps {
  segments: StatuslineSegment[]
  separator: string
}

function PreviewPanel({ segments, separator }: PreviewPanelProps) {
  const line1 = segments.filter((s) => s.enabled && s.line !== 2)
  const line2 = segments.filter((s) => s.enabled && s.line === 2)

  function renderLine(segs: StatuslineSegment[]) {
    const visible = segs.filter((s) => SEGMENT_MOCK[s.name as SegmentName] !== null)
    return visible.map((seg, i) => {
      const mock = SEGMENT_MOCK[seg.name as SegmentName]
      const sep = seg.separator ?? separator
      return (
        <span key={seg.name}>
          <span style={{ color: ansiToCSS(seg.color) }}>{mock}</span>
          {i < visible.length - 1 && <span style={{ color: '#555', opacity: 0.6 }}>{sep}</span>}
        </span>
      )
    })
  }

  return (
    <Stack gap='xs'>
      <Text
        fw={500}
        size='sm'
      >
        Preview
      </Text>
      <Paper
        p='md'
        style={{
          background: '#1a1a1a',
          borderRadius: 6,
          fontFamily: 'var(--font-jetbrains-mono, monospace)',
          fontSize: 13,
          minHeight: 48,
        }}
      >
        {line1.length === 0 && line2.length === 0 ? (
          <Text
            c='dimmed'
            size='xs'
          >
            No enabled segments
          </Text>
        ) : (
          <Stack gap={4}>
            {line1.length > 0 && <div style={{ color: '#d4d4d4' }}>{renderLine(line1)}</div>}
            {line2.length > 0 && <div style={{ color: '#d4d4d4' }}>{renderLine(line2)}</div>}
          </Stack>
        )}
      </Paper>
      <Text
        c='dimmed'
        size='xs'
      >
        Mock values — not live data
      </Text>
    </Stack>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Main page
// ─────────────────────────────────────────────────────────────────────────────

export function StatuslinePage() {
  const { data: remote, isLoading, refetch } = useStatuslineConfig()
  const save = useSaveStatuslineConfig()

  const [segments, setSegments] = useState<StatuslineSegment[]>([])
  const [separator, setSeparator] = useState(' │ ')
  const [dirty, setDirty] = useState(false)

  // Sync local state when remote data arrives (initial load or after reset)
  useEffect(() => {
    if (!remote) return
    setSegments(remote.segments)
    setSeparator(remote.separator)
    setDirty(false)
  }, [remote])

  const handleSegmentChange = useCallback((index: number, updates: Partial<StatuslineSegment>) => {
    setSegments((prev) => prev.map((s, i) => (i === index ? { ...s, ...updates } : s)))
    setDirty(true)
  }, [])

  const handleRemove = useCallback((index: number) => {
    setSegments((prev) => prev.filter((_, i) => i !== index))
    setDirty(true)
  }, [])

  const handleReorder = useCallback((next: StatuslineSegment[]) => {
    setSegments(next)
    setDirty(true)
  }, [])

  const { handleDragOver, handleDragStart, handleDrop } = useDragReorder(segments, handleReorder)

  function handleAdd(name: string) {
    if (segments.some((s) => s.name === name)) {
      notifications.show({
        color: 'orange',
        message: `${name} is already in the list`,
        title: 'Segment already present',
      })
      return
    }
    setSegments((prev) => [...prev, { color: null, enabled: true, line: 1, name, separator: null }])
    setDirty(true)
  }

  async function handleSave() {
    try {
      const result = await save.mutateAsync({ segments, separator })
      if (!result.ok) {
        notifications.show({ color: 'red', message: result.error ?? 'Unknown error', title: 'Save failed' })
        return
      }
      notifications.show({ color: 'green', message: 'Statusline config saved to disk', title: 'Saved' })
      setDirty(false)
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Unknown error'
      notifications.show({ color: 'red', message: msg, title: 'Save failed' })
    }
  }

  function handleReset() {
    void refetch()
    setDirty(false)
  }

  function handleCopyToml() {
    const toml = configToToml(segments, separator)
    navigator.clipboard
      .writeText(toml)
      .then(() => {
        notifications.show({ color: 'blue', message: 'TOML copied to clipboard', title: 'Copied' })
      })
      .catch(() => {
        notifications.show({ color: 'red', message: 'Clipboard write failed', title: 'Copy failed' })
      })
  }

  const unusedSegments = ALL_SEGMENT_NAMES.filter((name) => !segments.some((s) => s.name === name))

  if (isLoading) {
    return (
      <Stack>
        <Title order={2}>Statusline Editor</Title>
        <Text c='dimmed'>Loading config...</Text>
      </Stack>
    )
  }

  return (
    <Stack>
      <Group justify='space-between'>
        <Group gap='xs'>
          <Title order={2}>Statusline Editor</Title>
          {dirty && (
            <Badge
              color='orange'
              variant='light'
            >
              Unsaved changes
            </Badge>
          )}
          {remote && !remote.exists && (
            <Badge
              color='gray'
              variant='outline'
            >
              Using defaults
            </Badge>
          )}
        </Group>
        <Group gap='xs'>
          <Tooltip label='Copy TOML to clipboard'>
            <ActionIcon
              onClick={handleCopyToml}
              variant='light'
            >
              <IconCopy size={16} />
            </ActionIcon>
          </Tooltip>
          <Button
            disabled={!dirty}
            leftSection={<IconRefresh size={14} />}
            onClick={handleReset}
            size='xs'
            variant='default'
          >
            Reset
          </Button>
          <Button
            disabled={!dirty}
            loading={save.isPending}
            onClick={() => void handleSave()}
            size='xs'
          >
            Save
          </Button>
        </Group>
      </Group>

      {remote?.config_path && (
        <Text
          c='dimmed'
          size='xs'
        >
          {remote.config_path}
        </Text>
      )}

      <Divider />

      <Box
        style={{
          display: 'grid',
          gap: 16,
          gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
        }}
      >
        {/* Left panel — segment list */}
        <Card
          p='md'
          withBorder
        >
          <Stack gap='sm'>
            <Group justify='space-between'>
              <Text
                fw={600}
                size='sm'
              >
                Segments
              </Text>
              <Text
                c='dimmed'
                size='xs'
              >
                Drag to reorder
              </Text>
            </Group>

            <TextInput
              description='Shown between segments in the statusline'
              label='Separator'
              onChange={(e) => {
                setSeparator(e.currentTarget.value)
                setDirty(true)
              }}
              size='xs'
              value={separator}
            />

            <Divider />

            <Stack gap='xs'>
              {segments.map((seg, i) => (
                <SegmentRow
                  index={i}
                  key={seg.name}
                  onChange={handleSegmentChange}
                  onDragOver={handleDragOver}
                  onDragStart={handleDragStart}
                  onDrop={handleDrop}
                  onRemove={handleRemove}
                  segment={seg}
                />
              ))}
            </Stack>

            {unusedSegments.length > 0 && (
              <Select
                clearable
                data={unusedSegments.map((name) => ({ label: name, value: name }))}
                label='Add segment'
                leftSection={<IconPlus size={14} />}
                onChange={(v) => {
                  if (v) handleAdd(v)
                }}
                placeholder='Select a segment to add'
                size='xs'
                value={null}
              />
            )}
          </Stack>
        </Card>

        {/* Right panel — live preview */}
        <Card
          p='md'
          withBorder
        >
          <PreviewPanel
            segments={segments}
            separator={separator}
          />
        </Card>
      </Box>
    </Stack>
  )
}
