/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as SymbolsRouteImport } from './routes/symbols'
import { Route as StatuslineRouteImport } from './routes/statusline'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SnapshotRouteImport } from './routes/snapshot'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as MemoirsRouteImport } from './routes/memoirs'
import { Route as MemoirGraphRouteImport } from './routes/memoir-graph'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as CodeRouteImport } from './routes/code'
import { Route as CanopyRouteImport } from './routes/canopy'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SymbolsRoute = SymbolsRouteImport.update({
  id: '/symbols',
  path: '/symbols',
  getParentRoute: () => rootRouteImport,
} as any)
const StatuslineRoute = StatuslineRouteImport.update({
  id: '/statusline',
  path: '/statusline',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotRoute = SnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoirsRoute = MemoirsRouteImport.update({
  id: '/memoirs',
  path: '/memoirs',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoirGraphRoute = MemoirGraphRouteImport.update({
  id: '/memoir-graph',
  path: '/memoir-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const CanopyRoute = CanopyRouteImport.update({
  id: '/canopy',
  path: '/canopy',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/canopy': typeof CanopyRoute
  '/code': typeof CodeRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/lessons': typeof LessonsRoute
  '/memoir-graph': typeof MemoirGraphRoute
  '/memoirs': typeof MemoirsRoute
  '/memories': typeof MemoriesRoute
  '/onboard': typeof OnboardRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/snapshot': typeof SnapshotRoute
  '/status': typeof StatusRoute
  '/statusline': typeof StatuslineRoute
  '/symbols': typeof SymbolsRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/canopy': typeof CanopyRoute
  '/code': typeof CodeRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/lessons': typeof LessonsRoute
  '/memoir-graph': typeof MemoirGraphRoute
  '/memoirs': typeof MemoirsRoute
  '/memories': typeof MemoriesRoute
  '/onboard': typeof OnboardRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/snapshot': typeof SnapshotRoute
  '/status': typeof StatusRoute
  '/statusline': typeof StatuslineRoute
  '/symbols': typeof SymbolsRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/canopy': typeof CanopyRoute
  '/code': typeof CodeRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/lessons': typeof LessonsRoute
  '/memoir-graph': typeof MemoirGraphRoute
  '/memoirs': typeof MemoirsRoute
  '/memories': typeof MemoriesRoute
  '/onboard': typeof OnboardRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/snapshot': typeof SnapshotRoute
  '/status': typeof StatusRoute
  '/statusline': typeof StatuslineRoute
  '/symbols': typeof SymbolsRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/canopy'
    | '/code'
    | '/diagnostics'
    | '/lessons'
    | '/memoir-graph'
    | '/memoirs'
    | '/memories'
    | '/onboard'
    | '/sessions'
    | '/settings'
    | '/snapshot'
    | '/status'
    | '/statusline'
    | '/symbols'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/canopy'
    | '/code'
    | '/diagnostics'
    | '/lessons'
    | '/memoir-graph'
    | '/memoirs'
    | '/memories'
    | '/onboard'
    | '/sessions'
    | '/settings'
    | '/snapshot'
    | '/status'
    | '/statusline'
    | '/symbols'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/canopy'
    | '/code'
    | '/diagnostics'
    | '/lessons'
    | '/memoir-graph'
    | '/memoirs'
    | '/memories'
    | '/onboard'
    | '/sessions'
    | '/settings'
    | '/snapshot'
    | '/status'
    | '/statusline'
    | '/symbols'
    | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CanopyRoute: typeof CanopyRoute
  CodeRoute: typeof CodeRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  LessonsRoute: typeof LessonsRoute
  MemoirGraphRoute: typeof MemoirGraphRoute
  MemoirsRoute: typeof MemoirsRoute
  MemoriesRoute: typeof MemoriesRoute
  OnboardRoute: typeof OnboardRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SnapshotRoute: typeof SnapshotRoute
  StatusRoute: typeof StatusRoute
  StatuslineRoute: typeof StatuslineRoute
  SymbolsRoute: typeof SymbolsRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symbols': {
      id: '/symbols'
      path: '/symbols'
      fullPath: '/symbols'
      preLoaderRoute: typeof SymbolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statusline': {
      id: '/statusline'
      path: '/statusline'
      fullPath: '/statusline'
      preLoaderRoute: typeof StatuslineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshot': {
      id: '/snapshot'
      path: '/snapshot'
      fullPath: '/snapshot'
      preLoaderRoute: typeof SnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoirs': {
      id: '/memoirs'
      path: '/memoirs'
      fullPath: '/memoirs'
      preLoaderRoute: typeof MemoirsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoir-graph': {
      id: '/memoir-graph'
      path: '/memoir-graph'
      fullPath: '/memoir-graph'
      preLoaderRoute: typeof MemoirGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canopy': {
      id: '/canopy'
      path: '/canopy'
      fullPath: '/canopy'
      preLoaderRoute: typeof CanopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CanopyRoute: CanopyRoute,
  CodeRoute: CodeRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  LessonsRoute: LessonsRoute,
  MemoirGraphRoute: MemoirGraphRoute,
  MemoirsRoute: MemoirsRoute,
  MemoriesRoute: MemoriesRoute,
  OnboardRoute: OnboardRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SnapshotRoute: SnapshotRoute,
  StatusRoute: StatusRoute,
  StatuslineRoute: StatuslineRoute,
  SymbolsRoute: SymbolsRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
